### ISSUE TITLE
Log out/re-login in required for canvas to grab sessionsToken after team creation

### ISSUE THREAD

**Issue by bearcanrun** [AdvancedAlgos/MasterApp#19]
When a user creates a team, a sessionToken is added to their user data in the Users Module. However, for the canvas to be able to use this token, the user then has to log out and then back in.

The fix may be as simple as re-fetching the user from the UsersModule and updating local storage after team creation.

**Comment by Luis-Fernando-Molina** [comment]
> The fix may be as simple as re-fetching the user from the UsersModule and updating local storage after team creation.

Yes, but the problem is how does the Canvas realizes that it has to do that. It can either

1. Be doing it like crazy every n minutes
2. We need to implement a way to fire an event to the canvas, mechanism that later might be useful for other stuff. 

I would do 2, but I would have to think about how to implement it nicely.

**Comment by Luis-Fernando-Molina** [comment]
YOu can refresh the page on the meantime :-)

**Comment by Luis-Fernando-Molina** [comment]
The work needed at the master app for this issue was finished.
