### ISSUE TITLE
Invisible canvas over all

### ISSUE THREAD

**Issue by nikolabjelo** [AdvancedAlgos/MasterApp#57]
Sometime, while the canvas is loading (sometime for 30secs), an invisible canvas exists over the whole page. It blocks any clicks on the page. We should either not display it while it's loading, or showing a loading page.

**Comment by Luis-Fernando-Molina** [comment]
Do you know a way to reproduce this?

**Comment by nikolabjelo** [comment]
Hard reloading your page and limiting your bandwidth to 10kb/s might do the trick. Not sure though, it happens from time to time after a hard reload.

In any case, we should find a way to prioritize the master app download before the canvas (as it's much much lighter), and make the canvas download in the background on pages he is not needed on. As it would speed up things considerately on pages without the canvas, and wouldn't do much change on the chart page. (And usual user experience is to first create an account and then only visit the canvas)

**Comment by Luis-Fernando-Molina** [comment]
>  (And usual user experience is to first create an account and then only visit the canvas)

That is because now we are just creating and deleting teams for testing purposes, but once we are done with that, 90% of the time we will want to go to the canvas directly.

I would not enter in splitting the download just now until not knowing if this is a solution or a problem. 

Anyways, I will try to fix this issue, somehow.
