### ISSUE TITLE
Eliminate Hosts Module from NPM

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/MasterApp#58]
Since it was refactored to Events Module.

![image](https://user-images.githubusercontent.com/9479367/47910411-0e85ab00-de93-11e8-89d8-a2642b5bfa95.png)

**Comment by nikolabjelo** [comment]
We sadly cannot remove npmjs packages without human action on their part. We can send them an e-mail to ask them to remove it, but I think that deprecating it is enough. (mostly because we might reuse the same name for a real "host module" once we implement a system with leagues, competitions, ranking and whatever later)

I did deprecate it.
